accelerator: gpu
accumulate_grad_batches: 2
adjust_hrf: true
attn_drop_rate: 0
augment_during_training: false
augment_only_affine: false
augment_only_intensity: false
auto_lr_find: false
auto_scale_batch_size: false
bad_subj_path: null
batch_size: 4
c_multiplier: 2
check_val_every_n_epoch: 1
clf_head_version: v1
contrastive_type: 0
cycle: 0.3
dataset_name: HBN
dataset_split_num: 1
decoder: series_decoder
default_root_dir: output/moviefmri
depths:
- 2
- 2
- 6
- 2
detect_anomaly: false
devices: '1'
downstream_task: emotions
downstream_task_type: regression
embed_dim: 36
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
eval_batch_size: 4
experiment_name: 525_tune_seq30_2025-03-06_23-33-24
fast_dev_run: false
first_window_size:
- 4
- 4
- 4
- 4
freeze_feature_extractor: false
gamma: 1
grad_clip: false
id: rqvmz6lo
image_path: /data/HBN/3.3.1.movieDM_MNI_to_TRs_smooth_znorm_241120
img_size:
- 96
- 96
- 96
- 30
in_chans: 1
inference_mode: true
input_type: rest
label_scaling_method: standardization
last_layer_full_MSA: true
learning_rate: 5.0e-05
limit_training_samples: null
log_every_n_steps: 50
logger: true
loggername: wandb
max_epochs: 50
max_steps: -1
milestones:
- 100
- 150
model: swin4d_ver7
momentum: 0
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
num_classes: 1
num_heads:
- 3
- 6
- 12
- 24
num_nodes: 1
num_sanity_val_steps: 2
num_targets: 7
num_workers: 4
optimizer: AdamW
overfit_batches: 0
patch_size:
- 4
- 4
- 4
- 1
precision: 16
pretraining: false
project_name: moviefmri
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
scalability_check: false
seed: 1
sequence_length: 30
shuffle_time_sequence: false
strategy: ddp
stride_between_seq: 1
stride_within_seq: 1
sync_batchnorm: false
temperature: 0.1
test_only: false
track_grad_norm: -1
train_split: 0.7
use_contrastive: false
use_scheduler: false
val_split: 0.15
valid_only: true
weight_decay: 0.01
window_size:
- 4
- 4
- 4
- 4
with_voxel_norm: false
